

title: "MD. KHAIRUL BASHAR BHUIYAN"

email: "kbashar707@gmail.com"

description: >-
  MSc graduate in Computer Science with interests in
  machine learning, computer vision, and AI.

baseurl: "/my-git-projects"

url: "https://kbhuiyan13.github.io"

github_username: "KBhuiyan13"

theme: minima

plugins:
  - jekyll-feed

header_pages:
  - about.md
  - cv.md
  - publications.md
  - projects.md
  - awards.md
  - jobs.md
  - updates.md

sass:
  style: compressed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
